### ISSUE TITLE
[Question] Use own dataset

### ISSUE THREAD

**Issue by doantumy** [abaheti95/DC-NeuralConversation#2]
Hi, 

To train the model on our own dataset, do we only need to provide the simple text file where each line is corresponding to question and response in source and target file respectively?

Is it true that the opensubtitles source and target files are shuffled already?

Thanks.

**Comment by abaheti95** [comment]
Yes you are correct about the first question. You need 4 different files for training
s_train -> each line is source train sentence
t_train -> each line is target train sentence corresponding to the source train sentence
both these files should have same number of lines
s_val -> each line is source val sentence
t_val -> each line is target val sentence
First preprocess them and then train using that prepocessed files as described in the readme.

For second question, I don't know if they are already shuffled. I simply downloaded data from [jiweil/Neural-Dialogue-Generation](https://github.com/jiweil/Neural-Dialogue-Generation) and split them into 2 files as required by OpenNMT.
